### ISSUE TITLE
emitPropertyChange does not take low-level event apis into account

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-scripting-api#417] opened 2022-07-18 11:34 UTC
With the changes at #407 , the `emitPropertyChange` calls the read method on the property. However, it might be that I am subscribed to a temperature value over a serial connection and I would emit the temperature value as a property change once I detect it. Reading the property value would be redundant and might even give the wrong value if the temperature changes very quickly.

The gpio library at npm to control GPIOs of a Raspberry Pi has such a subscription API at https://www.npmjs.com/package/gpio#eventemitter . In this case, I would like to write the following code:
```js
gpio4.on("change", function(val) {
   // value will report either 1 or 0 (number) when the value changes
   console.log(val)
   myThing.emitPropertyChange(val);
});
```

With the current changes, the code would be:
```js
gpio4.on("change", function(val) {
   // value will report either 1 or 0 (number) when the value changes
   console.log(val)
   myThing.emitPropertyChange( );
   //internally, the following will happen via the readhandler
   let propertyVal = gpio4.get() //this is the same as val above if the gpio has not changed value
   return propertyVal
});
```

I find this to be not exactly optimal. The freedom to supply a value would be good and this can be the default behavior.

**Comment by danielpeintner** [comment] 2022-08-01 11:38
@egekorkan we seem to have misunderstandings again.
Could you please join again a call to clarify your expectations? 

* What about caching the value instead of calling gpio4.get() again?
* Notifications shouldn't  pass *large* values like streams etc. It should purely inform.

**Comment by egekorkan** [comment] 2022-08-01 12:09
I can join next week no problem. I can answer the first remark in advance, the second one I do not understand

> What about caching the value instead of calling gpio4.get() again?
That would be possible. The code above would write the new value to an internal variable at each change and readproperty handler would return that variable's value. In this case, there would be a sequence like: 
- detect change
- write to internal variable
- emitPropertyChange
  - read internal variable
  - emit internal variable value
  
Whereas before it would be:
- detect change
- emit changed value

The second one looks definitely shorter but it has one downside that it let's developers emit a property change without changing the property value. So the second one should probably be:
- detect change
- write to internal variable
- emit changed value

**Comment by zolkis** [comment] 2022-08-01 15:27
>  I would like to write the following code:

If in the example the value is not a number, but a long string or a stream, how would you like to write the code?
How would you specify (Web IDL, TypeScript) the API that would encapsulate all the possible data types?

In principle, the Scripting API should align to IoT network protocols before aligning to low level HW (i.e. local) APIs.

In general, the question is what use case is served end to end, and how does that use case play with other use cases as well.

Passing the value with the notification has problems over the network: race condition, possible redundancy when a hysteresis cannot be set, etc. It is much more flexible and simpler to have a fast control channel for notifications and a data channel for getting the values.

An API that reports a value with change notifications is possible, if 
- it is semantically clear that the value is _not_ guaranteed to be up to date in any given moment,
- large values (define this) are not transmitted, but eventually a link how to get them - but then how to do that with a uniform and consistent API (for which we have done that work by the reading API and now it would be duplicated).
If there is any proposals for such an API, we can take a look.

**Comment by ashimura** [comment] 2022-08-08 12:06
As the basis of the discussion for this issue, I'd suggest we clarify the environment of the expected setting, i.e., what kind of devices with what kind of sensors/actuators are connected with what kind of servers, what kind of data to be transferred from which to which and what kind of behavior on the server side and the device side is expected to discuss the detail of the related events, properties and actions.

**Comment by danielpeintner** [comment] 2022-08-08 13:15
Call 2022-08-08
@egekorkan will provide a more sophisticated example to look at.

**Comment by egekorkan** [comment] 2022-08-08 16:17
So I hope I can explain my point a bit better. I will give details on Kaz's comment above and then code examples (CODE EXAMPLES TO FOLLOW IN ANOTHER COMMENT DUE TO LACK OF TIME TODAY):
- Device: Any single board computer would be a valid device here, i.e. a Raspberry Pi or a more constrained devices like an ESP32
- Sensor attached: Anything with an on/off behavior: A clickable button, an emergency button, a light switch. A presence sensor might also be applicable. I will refer to this as a button from now on
- Actutator attached: Not necessary
- Network Architecture: The device (Thing) is an MQTT client, there is an MQTT broker somewhere (location not relevant), the Consumer is also an MQTT client. This scenario would also work with an HTTP Server Client model where the device is the server and consumer is the client. Longpoll subprotocol can be used in this case. 
- Data Transferred: State of the attached button. This can be a JSON string like "on" and "off".
- Device Behavior: The device has two main functions which I want to model as a single property affordance named `buttonState`:
  - Whenever the button is pressed or unpressed, it sends the state of the button as a payload, i.e. "on" or "off". This is observing the property `buttonState`
  - When requested by the Consumer, it sends the current state of the button as a payload, i.e. "on" or "off". This is reading the property `buttonState`
  - Note: I do not want to model these as two separate affordances where the button press is an event. This is a design choice.
- Consumer Behavior: The consumer is a dashboard. Upon initialization or reconnect, it reads the property value and displays it on the dashboard. Whenever the button is pressed, the dashboard value is updated. We can also imagine a case when the button is pressed, the Consumer sends an email to the factory manager, indicating a problem.

**Comment by zolkis** [comment] 2022-08-08 19:02
For the sake of discussing the problem, I will treat the example as if it had 3 random states. With only 2 states we have a sort of quantum entanglement: if we know the current state and that there was a state change, we instantly know the new state, even without reading :).

**Comment by relu91** [comment] 2022-12-17 15:24
I want to move forward with this issue and possibly converge on closing it. From my point of view there are two low-level API design cases:
1. Low-level API supports interaction by events (like the GPIO example above)
2. Low-level API **does not** supports interaction by events (like the GPIO example above)

I think the current design of the Scripting API supports both, quite well with minimal overheads.

### Support for events

Taking the scenario described above from @egekorkan, I would program an `ExposeThing` like the following:
```ts
//let's assume that I have this variable from the script context
const thing: ExposedThing;
let myProperty: number;
// initialize the cached property
myProperty = gpio.get()

thing.setReadHandler("myProperty", () => {
    return myProperty;
});

gpio4.on("change", function(val) {
   // value will report either 1 or 0 (number) when the value changes
   myProperty = val
   thing.emitPropertyChange( );
   //internally, node wot will call the function above
   // the overhead is caused by calling the function (but I would say is negligible)
}); 


``` 

### No supports for events

In this case, if the property can change for reasons outside the control of the `ExposedThing` (i.e. a sensor value reading). The `ExposedThing` should fallback to a polling behavior, but the overhead caused by the new design is pretty similar: a function call and an in-memory cached value:
```ts
//let's assume that I have this variable from the script context
const thing: ExposedThing;
let myProperty: number;
// initialize the cached property
myProperty = gpio.get()

thing.setReadHandler("myProperty", () => {
    return myProperty;
});

setInterval(()=> {
   const val = gpio.get()
   if( val != myProperty) {
       myProperty = val
       thing.emitPropertyChange( );
   }
}, 1000);
``` 
Note that in this scenario, I'm forced to use the cached value, cause otherwise, I wouldn't be able to understand if there was a change.

### My summary

Caching the value might represent a considerable overhead if the sensed value is a complex buffer of data, but this usually is not the case ( and when it does we are talking about complex things that are running on not-constrained devices). There is also the overhead caused by the additional step of calling the readHandler but I feel it to be negligible. I would wait until we get some real measurements on the impact of these overheads. 

What do you think @egekorkan? can we close this issue?

**Comment by relu91** [comment] 2022-12-19 13:01
From 19/12/2022 call:
- Need a better overview of hardware libraries and how they interact with low-level hardware. 
- @egekorkan right now the spec looks good, but it would be better to raise the awareness to developers about these conditions.

**Comment by egekorkan** [comment] 2022-12-19 14:08
Some other libraries that use the event or callback-driven approach:
- One joystick API example: https://github.com/balena-io-experimental/sense-joystick 
- JohnnyFive is a popular JS Framework for sensors and actuators programmed in JS. It seems to use the callback option quite heavily: http://johnny-five.io/api/thermometer/#usage and http://johnny-five.io/api/accelerometer/#usage

Are we considering non-JS options as well?

@ashimura suggested to find industrial examples but I am guessing that it would be difficult. Most open source libraries aim at DIY but I think we should take these more seriously since even we would use them to showcase the usage of Scripting API implementations in various events. Also, it would be a shame if we cannot show the use of Scripting API in the most trivial cases. There are some libraries for robotics etc. that are more industrial but they are not using callbacks much since it is more about actions (movements etc.) 

- Regarding an actual use of GPIO with a physical device, you can see our node-wot based implementation of an infrared sensor:
  - https://github.com/tum-esi/wot-sys/blob/master/Devices/nodewot-infrared-sensor-dobot/src/base.ts#L82 shows the old usage of writeproperty to trigger sending property value changes
  - See a similar setup by Volkswagen at https://www.youtube.com/watch?v=Jw00AcxFFJY . They could be using that sensor or something more advanced but they detect the model car with a sensor and stop the conveyor belt.

**Comment by relu91** [comment] 2023-01-23 12:39
> Edit: This issue can be still put into the spec as to the reason why there is a difference between emitEvent and emitPropertyChange

I agree that we can use this and summarize it for a short explainer inside the `emitPropertyChange` section. 

> IMHO this could be quite versatile. Implementations can choose to not provide the value, forcing the script to read. Or the script can choose to read anyway, even if a value exists. So the spec must tell that providing this value is "best effort", don't count it as an error if you don't get a value. Scoping it like that, I don't have any issues adding the optional value.

This design is still reasonable, I'm just afraid that it will open developers to make mistakes like forgetting to update the cached value (if any) or creating misalignments between the observed value and the one coming from reading it.

**Comment by egekorkan** [comment] 2023-01-25 13:06
> Developer needs to tell the WoT implementation to send a notification to observing clients (remote ConsumedThing objects) that "this property has changed, please re-read". That needs to be translated to a protocol message by the bindings.

This is not what is happening. `observeproperty` operation expects that a value is delivered. This operation without a value delivered is not semantically correct, it should be a specific event in this case.

**Comment by zolkis** [comment] 2023-01-25 13:34
> This operation without a value delivered is not semantically correct, it should be a specific event in this case. 

It is semantically correct with respect to the formulation "this property has changed, please re-read". The use case is for large data, streams etc. Also, for post-box architectures, where the data is not stored by the ExposedThing in question.

For small values, it makes sense to include the data as well.
These are both valid use cases.

If we mandate only one of the use cases, the other suffers for efficiency, latency, network bandwidth etc.
So the client ConsumedThing should be able to control this.

It means one more option to [observeProperty()](https://www.w3.org/TR/wot-scripting-api/#dom-consumedthing-observeproperty) and additional steps in its algorithm.

Note that on ExposedThing, the client can [insert](https://www.w3.org/TR/wot-scripting-api/#the-setpropertyobservehandler-method) an observe handler function that also provides the value with notifications. So the behavior is controlled by the script, which is correct.

If we were to update the client side API, the server side can adapt to the behavior requested by the client.

**Comment by egekorkan** [comment] 2023-01-25 13:44
Well the definition "this property has changed, please re-read" does not exist anywhere as far as I know. Second table at https://w3c.github.io/wot-thing-description/#form says "Identifies the observe operation on Property Affordances to be notified with the new data when the Property is updated."

Thus, "this property has changed, please re-read" needs a new operation from my point of view.

**Comment by zolkis** [comment] 2023-01-30 12:46
I propose we can move forward by providing this change,

```js
partial interface ExposedThing {
    Promise<undefined> emitPropertyChange(DOMString name, InteractionInput value);
} 
```

and I will create an issue at Use Cases and/or Architecture, to cover the use case of big payloads.

**Comment by relu91** [comment] 2023-01-30 12:48
Call Scripting API: 
- Needs more evaluation in terms of use cases and TD specification ( TD should state that there might be valueless notifications etc.) 
- Changes in the scripting interface-wise are minimal 
- @danielpeintner if big values are the problem -> this applies to events too
- @relu91 I would like to close this issue and discuss the new API problem in a dedicated issue. I feel that the initial problem is addressed. 



> I propose we can move forward by providing this change,
> 
> ```js
> partial interface ExposedThing {
>     Promise<undefined> emitPropertyChange(DOMString name, InteractionInput value);
> } 
> ```
> 
> and I will create an issue at Use Cases and/or Architecture, to cover the use case of big payloads.

I think there were reasons why we removed that, I'll be back with links to the relevant changes/discussion.

**Comment by relu91** [comment] 2023-01-30 12:50
I'm fine with having the `optional` to support user-defined values, but we should warn the implementers about the shortcomings found in this issue.

**Closed** 2023-02-20 12:51 UTC
Labels: API-improvement, need-pr
